Apa itu reduksi dimensi?

Reduksi dimensi adalah mengurangi dimensi dari data originalnya

Misalnya ketika kita melihat bayangan kita, bayangan adalah wujud 2 dimensi dari wujud 3 dimensi kita

Apa itu informasi yang hilang?

Seperti ngefoto sebuah rumah dari luar, informasi yang hilang adalah furnitur yang ada di dalam rumah namun tidak ikut terpotret

LINEAR TRANSFORMATION

Bisa dicontohkan dengan analogi function y=f(x) untuk memahami transformasi linear

x kecil adalah simbol bilangan

X besar adalah simbol matriks

Karena X dapat dianggap sebagai sebuah data karena berbentuk matriks

REAL SPACE

f:X -> Y 

Artinya adalah f:X bertransformasi menjadi Y

Sama dengan f(x) = y

f:X -> Y;f(x) = y


VECTOR SPACE

T:V -> W ; T(v) = w

v kecil namun tercetak tebal adalah simbol vector

INGAT!

Pada perkalian antar matriks, hukumnya adalah baris matriks A dikalikan ke kolom matriks B, ROW dikalikan ke COLUMN

Jika matriks A yg berukuran 2x2 dikalikan matriks B yg berukuran 2x1, maka hasilnya adalah matriks C yg berukuran 2x1

Eigen value dilambangkan simbol lambda yang berbentuk skalar

Eigencomposition adalah cara untuk mengubah matriks menjadi bilangan skalar

I adalah identitas terhadap sebuah matrix, suatu angka yang tidak dapat diubah

Cari tau angka identitas!

tujuh pangkat -1 sama dengan 1 per 7

## CARI INFORMASI SEPUTAR EIGENCOMPOSITION DI YOUTUBE

In [2]:
import numpy as np
from numpy.linalg import eig

In [4]:
A = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
values, vectors = eig(A)

print(values)

print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Pelajari cara mengubah data dari graph ke matriks