Ingat, matriks adalah sekumpulan vector

Vector adalah 1 dimensi array, sedangkan Matrix adalah 2 dimensi array yang terdiri dari row dan column
Bayangkan matrix seperti table berbentuk kotak yang berisikan value pada setiap koordinat row dan column nya

Kita import dulu numpy nya

In [3]:
import numpy as np

Contoh vector

Ingat urutannya, a1 adalah elemen 1, a2 adalah elemen 2, a3 adalah elemen 3

In [6]:
a = np.array([1,2,3])

Kita akan mencari tau berapa dimensi vector ini

In [5]:
a.shape

(3,)

Jika jawabannya seperti diatas (3,) berarti menjelaskan matriks ini, yg hanya berisikan 1 vektor, adalah 1 dimensi.

Kalau di python, matrix dapat di input seperti ini untuk visualisasi:

In [7]:
a = [[1,2],[3,4],[5,6]]

A = np.array(a)
print(A)

[[1 2]
 [3 4]
 [5 6]]


atau

In [9]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

Ingat urutan baris dan kolom di python dimulai dari 0

Misalnya jika kita ingin mengetahui baris pertama pada sebuah matriks

In [10]:
A[0]

array([1, 2])

Atau ingin mengakses satu nilai spesifik pada matriks

Contoh ingin mengambil angka 2 pada variabel A

In [11]:
A[0,1]

2

Trus gimana kalau mw ngambil nilai kolom nya om??

Pake mantra ini:

In [12]:
A[:,1]

array([2, 4, 6])

Types of Matrix:

Square Matrix, x(m,m) , kalau kolom nya 3 maka baris nya 3 juga, pokoknya bentuk kotak sama sisi lha ya

Diagonal Matrix, np.diag(x) ,simpelnya menunjukkan nilai diagonal dari sebuah matrix

Identity Matrix, np.eye(shape),melihat bentuk matriks berdasarkan jumlah row dan column. Misal masukkan 3 jika ingin melihat contoh bentuk 3x3

Upper Triangle Matrix, np.triu(x) ,yang diambil adalah nilai diagonal dan semua elemen yang berada "diatas" kumpulan elemen diagonal tersebut

Lower Triangle Matrix, np.tril(x) , yang diambil adalah nilai diagonal dan semua elemen yang berada "dibawah" kumpulan elemen diagonal tersebut

In [14]:
C = np.array([[2,4,5,7],[0,1,2,3],[4,1,0,6],[2,3,1,1]])

C.shape

(4, 4)

Pada C.shape menjelaskan bahwa ada 2 dimensi dengan jumlah 4 row dan 4 column

Misalkan ingin melihat contoh bentuk matriks 3x3 menggunakan identity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Penjumlahan atau Pengurangan antar Matriks

Ingat, jumlah row dan column harus sama, misal ukuran 3x3 baru bisa disandingkan dengan matriks lain yg berukuran 3x3 juga, selain dari itu bakalan error

In [16]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

C = np.array([[0,1,2],[4,1,1],[2,1,6]])

B + C

array([[ 1,  3,  5],
       [ 8,  6,  7],
       [ 9,  9, 15]])

Penjumlahan atau Pengurangan Skalar ke Matriks

In [17]:
4 + B

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

Ada tiga cara untuk melakukan perkalian Matrix, yaitu;

Matrix Multiplication, contoh B * C

Matrix - Scalar, contoh B * 5

Hadamard Product, contoh  A = B * C , hampir ga ada bedanya ama matrix multiplication

Matrix - Matrix Multiplication, cukup ribet, ada part nya sendiri untuk dijelaskan

Matrix - Matrix  Multiplication

Aturannya adalah jumlah kolom di matriks pertama harus sama jumlahnya dengan jumlah baris di matriks ke dua

Contoh:

In [20]:
matrix_A = np.array([[1,0,1], [2,1,3]])
matrix_B = np.array([[1,2,1], [0,1,3], [2,4,1]])

print(matrix_A.dot(matrix_B))

[[ 3  6  2]
 [ 8 17  8]]


In [21]:
print(matrix_A@matrix_B)

[[ 3  6  2]
 [ 8 17  8]]


TRANSPOSE

Berfungsi untuk membalikkan row menjadi column dan column menjadi row

Gunakan .T untuk memanggil fungsi transpose di numpy

ATAU

Gunakan df.transpose() di pandas

Contoh:

In [23]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

info sekilas

Python object terbagi dua, yaitu attribut dan method

Inverse Matrix hanya dapat dilakukan dengan matriks yang berbentuk persegi

INVERSE MATRIKS

In [27]:
from numpy.linalg import inv

Atau bisa juga menggunakan fungsi ini:

# MATRIX DETERMINANT

Wesh baca ntar di kode id

# TENSOR

Tensor adalah multidimensional array matriks,

Misalnya kita memiliki 3x3x3 three dimensional tensor

In [33]:
T = np.array([
            [[1,0,2], [2,5,4], [1,1,1]],
            [[6,7,1], [0,2,4], [7,8,1]],
            [[1,1,3], [4,5,1], [2,3,7]]
])

print(T.shape)
print(T)

(3, 3, 3)
[[[1 0 2]
  [2 5 4]
  [1 1 1]]

 [[6 7 1]
  [0 2 4]
  [7 8 1]]

 [[1 1 3]
  [4 5 1]
  [2 3 7]]]
