In [19]:
import numpy as np

In [21]:
A = np.array([
    [1,-1],
    [6,4]
])

In [36]:
A

array([[ 1, -1],
       [ 6,  4]])

In [46]:
B = np.array([1,1])

In [54]:
C = A * B
C

array([[ 1, -1],
       [ 6,  4]])

In [55]:
c1 = np.array([1,-1])
c2 = np.array([6,4])

In [56]:
D = c1 + c2
D

array([7, 3])

## Dengan demikian, adalah benar bahwa eigenvector nya adalah 1/3 dan eigenvalue nya adalah 2