### IMPORT PUSTAKA

In [1]:
import numpy as np

### PROBLEMS 1

In [12]:
tensor = np.array(
    [
        [[23,50],[7,12],[75,21],[57,12]],
        [[57,67],[99,43],[87,26],[18,84]]

    ]
)

In [13]:
print(tensor)

[[[23 50]
  [ 7 12]
  [75 21]
  [57 12]]

 [[57 67]
  [99 43]
  [87 26]
  [18 84]]]


In [14]:
tensor.shape

(2, 4, 2)

In [20]:
tensor1 = np.array(
    [
        [[23,50],[7,12]],
        [[75,21],[57,12]],
        [[57,67],[99,43]],
        [[87,26],[18,84]]

    ]
)

In [21]:
tensor1

array([[[23, 50],
        [ 7, 12]],

       [[75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

In [22]:
tensor1.shape

(4, 2, 2)

### PROBLEMS 2

In [29]:
A = np.array(
    [
        [23,50,19],
        [7,12,109],
        [57,67,98]
    ]
)

B = np.array(
    [
    [17],
    [22],
    [19]
    ]
)

In [25]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [30]:
B

array([[17],
       [22],
       [19]])

In [31]:
A * B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [32]:
print(A.dot(B))

[[1852]
 [2454]
 [4305]]


In [33]:
print(A@B)

[[1852]
 [2454]
 [4305]]


### PROBLEMS 3

In [34]:
X = np.array(
    [
        [23,50,19],
        [7,12,109],
        [57,67,98]
    ]
)

In [35]:
X

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

TRANSPOSE

In [36]:
XT = X.transpose()

In [37]:
XT

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

DETERMINAN

In [39]:
print(np.linalg.det(X))

131344.0000000002


INVERSE

In [40]:
print(np.linalg.inv(X))

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
