### PERKENALAN

Reza Anshari Valiantono

FTDS Batch 007

### IMPORT LIBRARY

In [8]:
import numpy as np
import pandas as pd
import sympy as sym

### PROBLEMS 1

Mencari jaringan laman web yang terpenting dari soal yang telah diberikan

DATA LOADING

Pada script ini saya membentuk sebuah matriks probabilitas/probability matrix berdasarkan hubungan antar laman/matriks

In [20]:
P = np.array([
    [0, 0, 1/4, 1/4, 1/4, 1/4],
    [0, 0, 1/2, 1/2, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0],
    [1/2, 0, 0, 1/2, 0, 0],
    [0, 0, 0, 0, 1, 0]
])

MATHEMATICAL CALCULATIONS

Pertama-tama saya memastikan bahwa probabilitas untuk setiap baris matriks adalah 1

In [19]:
np.sum(P,axis=1)

array([1., 1., 1., 1., 1., 1.])

Dengan Numpy, saya mencari eigenvalue dan eigenvector dari matriks-matriks tersebut

In [12]:
eigen_vals, eigen_vecs = np.linalg.eig(P.T)
order_eigen_values = np.absolute(eigen_vals).argsort()[::-1]
eigen_vals = eigen_vals[order_eigen_values]
eigen_vecs = eigen_vecs[:, order_eigen_values]

In [13]:
eigen_vecs

array([[ 3.86694596e-01+0.j        ,  4.47213595e-01-0.31622777j,
         4.47213595e-01+0.31622777j, -2.35166247e-16+0.j        ,
         1.90231975e-16+0.j        ,  1.84005963e-16+0.j        ],
       [ 0.00000000e+00+0.j        ,  0.00000000e+00-0.j        ,
         0.00000000e+00+0.j        ,  0.00000000e+00+0.j        ,
         0.00000000e+00+0.j        ,  1.67743384e-19+0.j        ],
       [ 9.66736489e-02+0.j        , -7.45355992e-02+0.21081851j,
        -7.45355992e-02-0.21081851j, -4.08248290e-01+0.j        ,
         5.46038280e-01+0.j        ,  5.44624911e-01+0.j        ],
       [ 4.83368245e-01+0.j        ,  3.72677996e-01-0.10540926j,
         3.72677996e-01+0.10540926j,  8.16496581e-01+0.j        ,
        -7.98739263e-01+0.j        , -7.99131001e-01+0.j        ],
       [ 7.73389191e-01+0.j        , -6.70820393e-01-0.j        ,
        -6.70820393e-01+0.j        ,  4.89929681e-17+0.j        ,
        -3.05949189e-17+0.j        , -3.16529246e-17+0.j        ],
     

In [14]:
r = eigen_vecs[:, 0]

r

array([0.3866946 +0.j, 0.        +0.j, 0.09667365+0.j, 0.48336824+0.j,
       0.77338919+0.j, 0.09667365+0.j])

In [15]:
visits = 100 * np.real(r/np.sum(r))
visits

array([21.05263158,  0.        ,  5.26315789, 26.31578947, 42.10526316,
        5.26315789])

HASIL

Berdasarkan hasil yang diperoleh, laman ke-5 adalah laman yang terpenting

### PROBLEMS 2

Berapakah kecepatan mobil uji Tesla pada 1,5 jam pertama?

MATHEMATICAL CALCULATIONS

Pertama-tama kita akan mencari turunan nya terlebih dahulu

In [23]:
t = sym.Symbol('t', real=True)

X = 2*t**3 - 3*t**2 - 5*t + 6

X.diff(t)

6*t**2 - 6*t - 5

Setelah turunannya didapatkan, maka kita dapat menghitung velocity/kecepatan mobil uji Tesla setelah 1,5 jam berlalu

V(t) = 6t^2 -6t - 5
V(t) = 6(2t) - 6

Jika t = 1,5 
Maka :

V(1,5) = 12(1,5) - 6
V(1,5) = 18 - 6
V(1,5) = 15

Jadi, setelah 1,5 jam, kecepatan mobil uji adalah 15 meter per detik atau 54 kpj